# Generated by Django 3.2.12 on 2022-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_seats',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
