# Generated by Django 3.2.12 on 2022-04-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_book_no_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='nos',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='route',
            name='dest',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
